[package]
name = "persister"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common", features = ["kafka"] }
browser = { path = "../browser" }
tokio-util = "0.7.15"
tokio = { version = "1.45.1", features = ["full"] }
tracing = "0.1.41"
diesel = { version = "2.2.10", features = ["postgres"] }
diesel-async = { version = "0.6.1", features = ["deadpool", "postgres"] }
dotenvy = "0.15.7"
thiserror = "2.0.12"
uuid = { version = "1.17.0", features = ["v4"] }
futures = "0.3.31"
