external_info:
  host: "brd.superproxy.io"
  port: 33335
  username_base: `replace_me`
  password: `replace_me`

filter_domains:
  - "www.copart.ca"
  - "copart.ca"
  - "www.copart.com"
  - "copart.com"
  - "cs.copart.com"
  - "wp.pl"
  - "www.wp.pl"
  - "geo.brdtest.com"
  - "echo.free.beeceptor.com"